# docker-compose.yml
# version: '3.1'
services:
  web:
    image: odoo:17.0
    container_name: odoo17_web
    depends_on:
      - db
    ports:
      - "8069:8069" # Odoo web port
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./custom-addons:/mnt/extra-addons # <-- IMPORTANT: Map your custom addons here
      - ./odoo-config:/etc/odoo # Optional: for custom odoo.conf
    environment:
      - HOST=db
      - PORT=5432
      - USER=odoo
      - PASSWORD=myodoo_password # Use a strong password
    # command: -- --dev=all # Uncomment for development mode (reloads python/xml)

  db:
    image: postgres:13
    container_name: odoo17_db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=myodoo_password # Use the same password as above
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata

volumes:
  odoo-web-data:
  odoo-db-data: